### ISSUE TITLE
macOSLAPS Management page doesn't appear

### ISSUE THREAD

**Issue by guillaumoplatte** [munkireport/laps#5] opened 2019-05-06 09:14 UTC
I've imported the macOSLAPS module.
The management page cannot be accessed from the Admin dropdown menu, whereas the listing page pages can be.

**Comment by tuxudo** [comment] 2019-05-06 09:38
It will not show up until this PR is merged into MunkiReport: https://github.com/munkireport/munkireport-php/pull/1134

**Comment by guillaumoplatte** [comment] 2019-05-06 14:01
Ok, I made the changes, but now I have the other submenus displayed twice in 'Admin', and it is also said that the encryption key is not set (key that I have generated by clicking on the button and then added first in the .env file, then I tried in the config.php and then both) :-/

**Comment by tuxudo** [comment] 2019-05-06 15:19
You'll have to clear your cache to fix the admin menu problem. Are you able to see if clients are saving data in the macOSLAPs listing?

**Comment by guillaumoplatte** [comment] 2019-05-07 07:49
Admin menu problem solved. 
Regarding the data, it worked once, now not working anymore.
In munkireport log : "macOSLAPS return code: 1"
In macOSLAPS.log : "ERROR: 'NoneType' object has no attribute 'changePassword_toPassword_error_'"

**Comment by tuxudo** [comment] 2019-05-07 12:57
I'm not able to reproduce this error. What is the exact setup of this system? I suggest continuing this on the #munkireport channel on the MacAdmins Slack

**Comment by tuxudo** [comment] 2020-05-11 16:13
Issue resolved

**Closed as completed by tuxudo** 2020-05-11 16:13 UTC
